package Main.Model.Stats;

/**
 * Created by Michael on 3/9/16.
 */
public enum StatsEnum {
    LIVES_LEFT, STRENGTH, AGILITY, INTELLECT, HARDINESS, EXPERIENCE, MOVEMENT, LEVEL, LIFE, MANA, OFFENSIVE_RATING, DEFENSIVE_RATING, ARMOR_RATING;
}
